language: elixir
elixir:
- 1.8.0
node_js:
- 10.3.0
script:
- mix test
- npm --prefix ./assets install
- npm --prefix ./assets test
deploy:
  provider: heroku
  api_key:
    secure: QOCBlmfZylZ6ZRp6ts0tUoOO5k8fKkwl8lHxtwt980cKhljUsqLqNhPDJcEH+WGRcTKBAhesu6XNg/JTm95dKkhmEGv+w6G1zO22/ngOIrLwkJSKpgtGA4WWfPPhUkAsludxBSK7MLn62bqbfuvoTa8/uxPJlQLz8KijhvUx4BLkE8EavZb38lbM46IPy+gFa+AhVVtJNybJpmcOGpZU9ymkaDuDlHZvHyFnoJJIjO2WRIQgcw2doZlP+TvDkFvNqvUdz8FubWaZCLcPwaArO7oCRkrAVFrqqe9/K+qKOmlbd5PaSjg0K8kFV/xUsjx4d1Di560ClrgRhOC4hirT016ROe+K0QoNBTXoxe4f6vDnAnDPH77RQ5JVrvUBC8mJZSsdpxZYsehVjpwHCUk7ez4g7Y9vx6yXRVczN6goMsTMchcb7p0behdIQqPy/sXSXc5cYBY5z/61hUAwSHLQWkkbDd0pR+pJLOrhQf2PQfnbxw77VZtrLCREIJ4kmt/ZgVN6jm/7gY45qcOSE6v54K06TeC3NLHYWUMN2+5MAOfQA0nTXnRmJXqJhqfQHCJRpRoEvOLbFS/7IZHMSdePPtEbrLmW73mhsx1TdlgHWMmgtz3XczkMU5uVPmedNZW4TzYWLAbN7M+SYLZA0xN5pWK9fJRg5Z7EyUxTR4c21WU=
